routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Notifications\NewUser;

Route::get('/', function () {
    return view('welcome');
    // return redirect()->route('login');
})->name('welcome');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/terms-conditions', 'HomeController@terms')->name('terms');
Route::get('/read-notification/{id}', 'HomeController@readNotification')->name('read-notif');

// PROFILE
Route::group(['prefix' => 'profile', 'as' => 'profile.'], function () {
    Route::get('/{user}', 'HomeController@profile')->name('index');
    Route::get('/edit/{user}', 'HomeController@changeProfile')->name('change');
});

// SETTINGS
Route::group(['prefix' => 'settings', 'as' => 'setting.'], function () {
    Route::get('/general', 'HomeController@general')->name('general');
    Route::get('/advance', 'HomeController@advance')->name('advance');
});

// CARS
Route::group(['prefix' => 'cars', 'as' => 'cars.'], function () {

    Route::get('/', 'CarController@index')->name('index');
    Route::get('/brands', 'BrandController@index')->name('brand');

    Route::get('/add', 'CarController@add')->name('add');
    Route::post('/new', 'CarController@create')->name('new');

    Route::get('/edit/{car}', 'CarController@edit')->name('edit');
    Route::post('/update', 'CarController@update')->name('update');

    Route::get('/delete/{car}', 'CarController@destroy')->name('delete');

    Route::get('/add/brand', 'BrandController@add')->name('add.brand');
    Route::post('/new/brand', 'BrandController@create')->name('new.brand');

    Route::get('/brand/edit/{brand}', 'BrandController@edit')->name('edit.brand');
    Route::post('/brand/update', 'BrandController@update')->name('update.brand');

    Route::get('/brand/delete/{brand}', 'BrandController@destroy')->name('delete.brand');

    Route::get('/detail/{car}/{notif_id?}', 'CarController@detail')->name('detail');

    Route::get('/search', 'CarController@search')->name('search');

    Route::get('/borrow/{car}', 'TransactionsController@borrow')->name('borrow');
    Route::post('/borrowing', 'TransactionsController@borrowing')->name('borrowing');
    Route::get('/borrowed/{type}', 'TransactionsController@borrowed')->name('borrowed');
});

// TRANSACTIONS
Route::group(['prefix' => 'transactions', 'as' => 'trans.'], function () {
    Route::get('/', 'TransactionsController@index')->name('index');
    Route::get('/borrowed/{type}', 'TransactionsController@borrowed')->name('borrowed');

    Route::get('/add/{trans}', 'TransactionsController@add')->name('add');
    Route::post('/new', 'TransactionsController@new')->name('new');

    Route::get('/edit/{trans}', 'TransactionsController@edit')->name('edit');
    Route::post('/update/{trans}', 'TransactionsController@update')->name('update');

    Route::get('/search', 'TransactionsController@search')->name('search');

    Route::get('/take/{trans}', 'TransactionsController@accept')->name('accept');

    Route::get('/delete/{trans}', 'TransactionsController@destroy')->name('delete');

    Route::get('/invoice/{trans}', 'TransactionsController@invoice')->name('invoice');
});

// USERS
Route::group(['prefix' => 'users', 'as' => 'users.'], function () {
    Route::get('/', 'UsersController@index')->name('index');
    Route::get('/workers', 'UsersController@workers')->name('workers');

    Route::get('/profile/{user}', 'UsersController@profile')->name('profile');

    Route::get('/add/{user}', 'UsersController@add')->name('workers.add');
    Route::post('/new', 'UsersController@new')->name('workers.new');

    Route::get('/edit/{user}', 'UsersController@edit')->name('edit');
    Route::post('/update', 'UsersController@update')->name('update');

    Route::get('/search', 'CarController@search')->name('search');

    Route::get('/hire/{user}', 'UsersController@hire')->name('hire');
    Route::get('/kick/{user}', 'UsersController@kick')->name('kick');

    Route::get('/verif/{user}/{type}', 'UsersController@verif')->name('verif');
});


Route::get('/testnotif', function () {
    // Auth::user()->notify(new NewUser(User::find(1)));
    dd(substr(Auth::user()->notifications->first()->type, 18));
})->name('testnotif');

app/Http/Controllers/TransactionsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Auth;
use DateTime;
use App\Transaction;
use App\Detail;
use App\Car;
use App\Borrow;

class TransactionsController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        if(!Auth::user()->isUser()){
            $data['transactions'] = Transaction::paginate(5);
        } else {
            $data['transactions'] = Transaction::where('id_user', Auth::user()->id)->paginate(5);    
        }

        return view('transactions.index', $data);
    }

    public function borrowed($type)
    {
        
        if($type == 'recent'){
            $status = "belum diambil";
        } else {
            $status = "sudah diambil";
        }

        $data['transactions'] = Transaction::where('user_id', Auth::user()->id)->where('status', $status)->paginate(5);
        // $data['transactions'] = Transaction::whereRaw('user_id = ' . Auth::user()->id . ' and status = \''. $status . '')->paginate(5);

        return view('transactions.borrowed', $data);
    }
    public function borrow($id)
    {
        $data['car'] = Car::find($id);

        return view('transactions.borrow', $data);
    }

    public function borrowing(Request $request)
    {
        $prev_trans = 

        $date_first = new DateTime($request->date_first);
        $date_last = new DateTime($request->date_last);
        
        $car_id = $request->car_id;
        $user_id = Auth::user()->id;

        $price = (int) str_replace(',','',$request->price);
        $status = "belum diambil";

        if ($date_first > $date_last) {
            return redirect()->back()->with('fail', 'Tanggal Awal Lebih Besar!');
        }

        $length = $date_first->diff($date_last)->days;
        $total = (($length > 0)? $length : 1) * $price;
        // dd($total);

        $trans = new Transaction;
        $trans->date_first = $date_first->format('Y-m-d');
        $trans->date_last = $date_last->format('Y-m-d');
        $trans->user_id = $user_id;
        $trans->car_id = $car_id;
        $trans->status = $status;
        $trans->total_price = $total;

        if($trans->save()){
            return redirect()->route('cars.index')->with('success', 'Mobil Berhasil Dipinjam!');
        }

        return redirect()->back()->with('fail', 'Mobil Gagal Dipinjam!');
    }

    public function invoice(Transaction $trans)
    {
        $data['trans'] = $trans;
        $first = new DateTime($trans->date_first);
        $last = new DateTime($trans->date_last);
        $period = $first->diff($last);
        $duration = $period->m . ' months, ' . $period->days . ' days, ' . $period->h . ' hours.';
        $data['duration'] = $duration;

        return view('transactions.invoice', $data);
    }

    public function accept(Transaction $trans)
    {
        $trans->status = "sudah diambil";
        if ($trans->save()) {
            return redirect()->route('trans.index')->with('success', 'Transaksi Telah Selesai!');
        }
        return redirect()->back()->with('fail', 'Transaksi Gagal Diselesaikan!');
    }

    public function destroy(Transaction $trans)
    {
        if ($trans->delete) {
            return redirect()->route('trans.index')->with('success', 'Transaksi Berhasil Digagalkan!');
        }

        return redirect()->back()->with('fail', 'Transaksi Gagal Dihapus!');
    }
}

resources/views/transactions/borrow.blade.php
@extends('layouts.master')
@section('meta-content')
    Transactions - Add
@endsection

@push('css')
    {{-- <link rel="stylesheet" href="{{asset('css/summernote-bs4.css')}}"> --}}
    <link rel="stylesheet" href="{{asset('css/daterangepicker.css')}}">
@endpush

@section('content')
    <div class="section-body">
        <h2 class="section-title">Pinjam Mobil</h2>
        <p class="section-lead">Halaman Pinjam Mobil</p>
        <div class="card">
            <div class="card-header">
                <div class="card-header-action">
                    <a href="{{ url()->previous() }}" class="btn btn-primary btn-lg"><i class="fas fa-arrow-left"></i>&nbsp; Back</a>
                </div>
            </div>
            <div class="card-body">
                <form action="{{route('cars.borrowing')}}" method="POST">
                    @csrf
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3 pt-2">Tanggal Pinjam</label>
                        <div class="col-sm-12 row col-md-7">
                            <div class="col-md-5 col-sm-12">
                                <input type="text" name="date_first" class="form-control datepicker">
                            </div>                            
                            <div class="col-1 col-lg-1 col-md-2 col-sm-12 pt-1 pb-1 mt-2 mb-2 text-center">To</div>
                            <div class="col-md-5 col-sm-12">
                                <input type="text" name="date_last" class="form-control datepicker">
                            </div>
                        </div>
                    </div>
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3 pt-2">Car</label>
                        <div class="col-sm-12 col-md-7">
                            <input type="text" name="car" class="form-control" value="{{$car->name}}" readonly>
                            <input type="text" name="car_id" class="form-control" value="{{$car->id}}" hidden>
                        </div>
                    </div>
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3 pt-2">Currency</label>
                        <div class="input-group col-sm-12 col-md-7">
                            <div class="input-group-prepend">
                                <div class="input-group-text">
                                    Rp.
                                </div>
                            </div>
                            <input type="text" name="price" value="{{$car->price}}" class="form-control currency" readonly>
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    / day
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-12 col-md-10 text-md-right">
                            <button type="submit" class="btn btn-success"><i class="fas fa-car-side"></i>&nbsp; Borrow Car</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection


@push('js')
    <script src="{{asset('js/daterangepicker.js')}}"></script>
    <script src="{{asset('js/cleave.min.js')}}"></script>
    <script>
        "use strict";

        var cleaveC = new Cleave('.currency', {
            numeral: true,
            numeralThousandsGroupStyle: 'thousand'
            });
    </script>
@endpush

resources/views/transactions/borrowed.blade.php
@extends('layouts.master')
@section('meta-content')
    Transactions
@endsection
@section('content')
    <div class="section-body">
        <h2 class="section-title">Halaman Transaksi</h2>
            <p class="section-lead">Berisi semua data transaksi milikmu</p>
        <div class="card">
                <div class="card-header">
                    <a href="{{route('cars.index')}}" class="btn btn-warning btn-lg"><i class="fas fa-plus"></i>&nbsp; Tambah</a>
                    <h4></h4>
                    <div class="card-header-form">
                        <form>
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Search">
                            <div class="input-group-btn">
                            <button class="btn btn-info"><i class="fas fa-search"></i></button>
                            </div>
                        </div>
                        </form>
                    </div>
                </div>
                <div class="card-body p-0">
                    <div class="table-responsive">
                        @if(count($transactions) > 0)
                            <table class="table table-hover">
                                <thead class="table-thead">
                                    <tr>
                                        <th>Id</th>
                                        <th>Tanggal Pinjam</th>
                                        <th>Tanggal Kembali</th>
                                        <th>Mobil</th>
                                        <th>Total Harga</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody class="table-tbody">
                                    @foreach ($transactions as $trans)
                                        <tr>
                                            <td>{{$trans->id}}</td>
                                            <td>{{$trans->date_first}}</td>
                                            <td>{{$trans->date_last}}</td>
                                            <td>{{$trans->car->name}}</td>
                                            <td>{{$trans->getPrice()}}</td>
                                            <td>
                                                <a href="{{route('trans.invoice', [$trans->id])}}" class="btn btn-secondary btn-action mr-1" data-toggle="tooltip" title="detail"><i class="fas fa-eye"></i></a>
                                                @if (Auth::user()->isWorker() && $trans->user_id != Auth::user()->id)
                                                    <a href="{{route('trans.edit', [$trans->id])}}" class="btn btn-primary btn-action mr-1" data-toggle="tooltip" title="Edit"><i class="fas fa-pencil-alt"></i></a>
                                                @endif
                                                <a href="{{route('trans.delete', [$trans->id])}}" class="btn btn-danger btn-action btn-delete" data-toggle="tooltip" title="Delete"><i class="fas fa-trash"></i></a>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                            <div class="float-right pr-3">
                                {{$transactions->links()}}
                            </div>
                        @else
                            <div class="col-md-12 text-center mt-5">
                                <h3 class="title">Data Masih Kosong!</h3>
                                <a href="{{route('cars.index')}}" class="btn btn-lg btn-success mt-2 mb-5">Pinjam Mobil</a>
                            </div>
                        @endif
                    </div>
                </div>
            </div>
    </div>
@endsection

resources/views/transactions/index.blade.php
@extends('layouts.master')
@section('meta-content')
Transactions
@endsection
@section('content')
<div class="section-body">
    <h2 class="section-title">Halaman Transaksi</h2>
    @if (Auth::user()->isWorker())
    <p class="section-lead">Berisi semua data transaksi yg terdata di database</p>
    @else
    <p class="section-lead">Berisi semua data transaksi milikmu</p>
    @endif
    <div class="card">
        <div class="card-header">
            <a href="{{route('cars.index')}}" class="btn btn-warning btn-lg"><i class="fas fa-plus"></i>&nbsp; Tambah</a>
            <h4></h4>
            <div class="card-header-form">
                <form>
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search">
                        <div class="input-group-btn">
                            <button class="btn btn-info"><i class="fas fa-search"></i></button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="card-body p-0">
            <div class="table-responsive">
                @if(count($transactions) > 0)
                <table class="table table-hover">
                    <thead class="table-thead">
                        <tr>
                            <th>Id</th>
                            <th>Peminjam</th>
                            <th>Tanggal Kembali</th>
                            <th>Status</th>
                            <th>Total Harga</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody class="table-tbody">
                        @foreach ($transactions as $trans)
                        <tr>
                            <td>{{$trans->id}}</td>
                            <td>{{$trans->user->name}}</td>
                            <td>{{$trans->date_last}}</td>
                            <td>{{$trans->status}}</td>
                            <td>{{$trans->getPrice()}}</td>
                            <td>
                                <a href="{{route('trans.invoice', [$trans->id])}}" class="btn btn-secondary btn-action mr-1" data-toggle="tooltip" title="detail"><i class="fas fa-eye"></i></a>
                                @if (Auth::user()->isWorker() && $trans->user_id != Auth::user()->id)
                                <a href="{{route('trans.edit', [$trans->id])}}" class="btn btn-primary btn-action mr-1" data-toggle="tooltip" title="Edit"><i class="fas fa-pencil-alt"></i></a>
                                @endif
                                @if ($trans->status == 'belum diambil')
                                <a href="{{route('trans.accept', [$trans->id])}}" class="btn btn-warning btn-action mr-1" data-toggle="tooltip" title="Take"><i class="fas fa-hands"></i></a>
                                @endif
                                <a href="{{route('trans.delete', [$trans->id])}}" class="btn btn-danger btn-action btn-delete" data-toggle="tooltip" title="Delete"><i class="fas fa-trash"></i></a>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
                <div class="float-right pr-3">
                    {{$transactions->links()}}
                </div>
                @else
                <div class="col-md-12 text-center mt-5">
                    <h3 class="title">Data Masih Kosong!</h3>
                    <a href="{{route('cars.index')}}" class="btn btn-lg btn-success mt-2 mb-5">Pinjam Mobil</a>
                </div>
                @endif
            </div>
        </div>
    </div>
</div>
@endsection
@push('js')
<script>
    $('.btn-accept').each(function (i) {
        const id = $(this).data('id');
        // const name = $(this).data('name');
        $(this).click(function(e){
            e.preventDefault();
            Swal.fire({
                title: 'Anda Yakin?',
                text: "Transaksi tidak dapat dibatalkan!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#47c363',
                cancelButtonColor: '#fc544b',
                confirmButtonText: 'Ya, Saya Yakin!'
            }).then((result) => {
                if (result.value) {
                    window.location = "{{url('/transactions/accept')}}" + '/' + id;
                } else if (result.dismiss === Swal.DismissReason.cancel){
                    Swal.fire(
                    'Woopss!',
                    'Transaksi tidak jadi selesai...',
                    'error'
                    );
                }
            });
        });
    });
</script>
@endpush

resources/views/transactions/invoice.blade.php
@extends('layouts.master')
@section('meta-content')
Invoice
@endsection

@push('css')
<style>
  @media print {
    @page {size: 290mm 230mm;}
    
    body * {
      visibility: hidden;
    }
    #section-to-print, #section-to-print * {
      visibility: visible;
    }
    #section-to-print {
      width: 100%;
      position:absolute;
      top: 0;
      left: 0;
      bottom: 0;
    }
  }
</style>
@endpush
@section('content')
<div class="section-body">
  <div class="invoice">
    <div class="invoice-print" id="section-to-print">
      <div class="row">
        <div class="col-lg-12">
          <div class="invoice-title">
            <h2>Invoice</h2>
            <div class="invoice-number">Order #{{$trans->id}}</div>
          </div>
          <hr>
          <div class="row">
            <div class="col-md-6">
              <address>
                <strong>Shipped To:</strong><br>
                {{$trans->user->name}}<br>
                {{$trans->user->email}}<br>
                {{$trans->user->address}}<br>
              </address>
            </div>
            <div class="col-md-6 text-md-right">
              <address>
                <strong>Order Date:</strong><br>
                {{$trans->created_at}}<br>
                <strong>Payment Method:</strong><br>
                On The Spot<br>
              </address>  
            </div>
          </div>
        </div>
      </div>
      
      <div class="row mt-4">
        <div class="col-md-12">
          <div class="section-title">Order Summary</div>
          <p class="section-lead">All items here cannot be deleted.</p>
          <div class="table-responsive">
            <table class="table table-striped table-hover table-md">
              <tr>
                <th data-width="40">#</th>
                <th>Item</th>
                <th class="text-center">Price</th>
                <th class="text-md-center">Duration</th>
                <th class="text-right">Total</th>
              </tr>
              <tr>
                <td>1</td>
                <td>{{$trans->car->name}}</td>
                <td class="text-center">{{$trans->car->getPrice()}}</td>
                <td class="text-md-center">{{$duration}}</td>
                <td class="text-right">{{$trans->getPrice()}}</td>
              </tr>
            </table>
          </div>
          <div class="row mt-4">
            <div class="col-lg-8">
              
            </div>
            <div class="col-lg-4 text-right">
              <div class="invoice-detail-item">
                <div class="invoice-detail-name">Subtotal</div>
                <div class="invoice-detail-value">{{$trans->getPrice()}}</div>
              </div>
              <div class="invoice-detail-item">
                <div class="invoice-detail-name">Shipping</div>
                <div class="invoice-detail-value">Rp. 0</div>
              </div>
              <hr class="mt-2 mb-2">
              <div class="invoice-detail-item">
                <div class="invoice-detail-name">Total</div>
                <div class="invoice-detail-value invoice-detail-value-lg">{{$trans->getPrice()}}</div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <hr>
    <div class="text-md-right">
      <div class="float-lg-left mb-lg-0 mb-3">
        <button class="btn btn-primary btn-icon icon-left btn-accept" data-id="{{$trans->id}}"><i class="fas fa-credit-card"></i> Process Payment</button>
        <button class="btn btn-danger btn-icon icon-left btn-cancel" data-id="{{$trans->id}}"><i class="fas fa-times"></i> Cancel</button>
      </div>
      <button class="btn btn-warning btn-icon icon-left" onclick="window.print()"><i class="fas fa-print"></i> Print</button>
    </div>
  </div>
</div>
@endsection
@push('js')
<script>
  $('.btn-accept').each(function (i) {
    const id = $(this).data('id');
    // const name = $(this).data('name');
    $(this).click(function(e){
      e.preventDefault();
      Swal.fire({
        title: 'Anda Yakin?',
        text: "Transaksi tidak dapat dibatalkan!",
        type: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#47c363',
        cancelButtonColor: '#fc544b',
        confirmButtonText: 'Ya, Saya Yakin!'
      }).then((result) => {
        if (result.value) {
          window.location = "{{url('/transactions/accept')}}" + '/' + id;
        } else if (result.dismiss === Swal.DismissReason.cancel){
          Swal.fire(
          'Woopss!',
          'Transaksi tidak jadi selesai...',
          'error'
          );
        }
      });
    });
  });

  $('.btn-cancel').each(function (i) {
    const id = $(this).data('id');
    $(this).click(function(e){
      e.preventDefault();
      Swal.fire({
        title: 'Anda Yakin?',
        text: "Transaksi akan dihapus!",
        type: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#47c363',
        cancelButtonColor: '#fc544b',
        confirmButtonText: 'Ya, Saya Yakin!'
      }).then((result) => {
        if (result.value) {
          window.location = "{{url('/transactions/accept')}}" + '/' + id;
        } else if (result.dismiss === Swal.DismissReason.cancel){
          Swal.fire(
          'Save~',
          'Data transaksi diselamatkan!',
          'success'
          );
        }
      });
    });
  });
</script>
@endpush