routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Notifications\NewUser;

Route::get('/', function () {
    return view('welcome');
    // return redirect()->route('login');
})->name('welcome');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/terms-conditions', 'HomeController@terms')->name('terms');
Route::get('/read-notification/{id}', 'HomeController@readNotification')->name('read-notif');

// PROFILE
Route::group(['prefix' => 'profile', 'as' => 'profile.'], function () {
    Route::get('/{user}', 'HomeController@profile')->name('index');
    Route::get('/edit/{user}', 'HomeController@changeProfile')->name('change');
});

// SETTINGS
Route::group(['prefix' => 'settings', 'as' => 'setting.'], function () {
    Route::get('/general', 'HomeController@general')->name('general');
    Route::get('/advance', 'HomeController@advance')->name('advance');
});

// CARS
Route::group(['prefix' => 'cars', 'as' => 'cars.'], function () {

    Route::get('/', 'CarController@index')->name('index');
    Route::get('/brands', 'BrandController@index')->name('brand');

    Route::get('/add', 'CarController@add')->name('add');
    Route::post('/new', 'CarController@create')->name('new');

    Route::get('/edit/{car}', 'CarController@edit')->name('edit');
    Route::post('/update', 'CarController@update')->name('update');

    Route::get('/delete/{car}', 'CarController@destroy')->name('delete');

    Route::get('/add/brand', 'BrandController@add')->name('add.brand');
    Route::post('/new/brand', 'BrandController@create')->name('new.brand');

    Route::get('/brand/edit/{brand}', 'BrandController@edit')->name('edit.brand');
    Route::post('/brand/update', 'BrandController@update')->name('update.brand');

    Route::get('/brand/delete/{brand}', 'BrandController@destroy')->name('delete.brand');

    Route::get('/detail/{car}/{notif_id?}', 'CarController@detail')->name('detail');

    Route::get('/search', 'CarController@search')->name('search');

    Route::get('/borrow/{car}', 'TransactionsController@borrow')->name('borrow');
    Route::post('/borrowing', 'TransactionsController@borrowing')->name('borrowing');
    Route::get('/borrowed/{type}', 'TransactionsController@borrowed')->name('borrowed');
});

// TRANSACTIONS
Route::group(['prefix' => 'transactions', 'as' => 'trans.'], function () {
    Route::get('/', 'TransactionsController@index')->name('index');
    Route::get('/borrowed/{type}', 'TransactionsController@borrowed')->name('borrowed');

    Route::get('/add/{trans}', 'TransactionsController@add')->name('add');
    Route::post('/new', 'TransactionsController@new')->name('new');

    Route::get('/edit/{trans}', 'TransactionsController@edit')->name('edit');
    Route::post('/update/{trans}', 'TransactionsController@update')->name('update');

    Route::get('/search', 'TransactionsController@search')->name('search');

    Route::get('/take/{trans}', 'TransactionsController@accept')->name('accept');

    Route::get('/delete/{trans}', 'TransactionsController@destroy')->name('delete');

    Route::get('/invoice/{trans}', 'TransactionsController@invoice')->name('invoice');
});

// USERS
Route::group(['prefix' => 'users', 'as' => 'users.'], function () {
    Route::get('/', 'UsersController@index')->name('index');
    Route::get('/workers', 'UsersController@workers')->name('workers');

    Route::get('/profile/{user}', 'UsersController@profile')->name('profile');

    Route::get('/add/{user}', 'UsersController@add')->name('workers.add');
    Route::post('/new', 'UsersController@new')->name('workers.new');

    Route::get('/edit/{user}', 'UsersController@edit')->name('edit');
    Route::post('/update', 'UsersController@update')->name('update');

    Route::get('/search', 'CarController@search')->name('search');

    Route::get('/hire/{user}', 'UsersController@hire')->name('hire');
    Route::get('/kick/{user}', 'UsersController@kick')->name('kick');

    Route::get('/verif/{user}/{type}', 'UsersController@verif')->name('verif');
});


Route::get('/testnotif', function () {
    // Auth::user()->notify(new NewUser(User::find(1)));
    dd(substr(Auth::user()->notifications->first()->type, 18));
})->name('testnotif');

resources/views/layouts/partials/footer.blade.php
<footer class="main-footer">
    <div class="footer-left">
        Copyright &copy; {{date('Y')}} <div class="bullet"></div> Make By <a href="#">Ferdyansyah Nur Rohim</a>
    </div>
    <div class="footer-right">
        0.8.4
    </div>
</footer>

resources/views/layouts/partials/navbar.blade.php
<div class="navbar-bg"></div>

    <nav class="navbar navbar-expand-lg main-navbar">
    <div class="form-inline mr-auto">
        <ul class="navbar-nav mr-3">
        <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a></li>
        <li><a href="#" data-toggle="search" class="nav-link nav-link-lg d-sm-none"><i class="fas fa-search"></i></a></li>
        </ul>
        
    </div>
    <ul class="navbar-nav navbar-right">
    <li class="dropdown dropdown-list-toggle"><a href="#" data-toggle="dropdown" class="nav-link notification-toggle nav-link-lg {{(Auth::user()->unreadNotifications->count() > 0)? 'beep' : ''}}"><i class="far fa-bell"></i></a>
        <div class="dropdown-menu dropdown-list dropdown-menu-right">
            <div class="dropdown-header">Notifications
            <div class="float-right">
                <a href="#">Mark All As Read</a>
            </div>
            </div>
            <div class="dropdown-list-content dropdown-list-icons">
            <a href="#" class="dropdown-item dropdown-item-unread">
                <div class="dropdown-item-icon bg-primary text-white">
                <i class="fas fa-code"></i>
                </div>
                <div class="dropdown-item-desc">
                Template update is available now!
                <div class="time text-primary">2 Min Ago</div>
                </div>
            </a>
            @if (Auth::user()->notifications)
                @foreach (Auth::user()->notifications as $notification)
                    @switch(substr($notification->type, 18))
                        @case('NewCar')
                            <a href="{{route('cars.detail', [$notification->data['car']['id'],$notification->id])}}" class="dropdown-item">
                                <div class="dropdown-item-icon bg-info text-white">
                                <i class="fas fa-car"></i>
                                </div>
                                <div class="dropdown-item-desc w-100">
                                {{$notification->data['car']['name']}} is available now!
                                <div class="time {{($notification->read_at)? : 'slow-beep'}}">{{$notification->created_at->diffForHumans()}}</div>
                                </div>
                            </a>
                            @break
                        @case('NewUser')
                            <a href="" class="dropdown-item">
                                <div class="dropdown-item-icon bg-info text-white">
                                <i class="far fa-user"></i>
                                </div>
                                <div class="dropdown-item-desc">
                                {{$notification->data['user']['name']}} has fully registered as new member!
                                <div class="time {{($notification->read_at)? : 'slow-beep'}}">{{$notification->created_at->diffForHumans()}}</div>
                                </div>
                            </a>
                            @break
                        @default
                            
                    @endswitch
                @endforeach
            @else

            @endif
            
            <a href="#" class="dropdown-item">
                <div class="dropdown-item-icon bg-success text-white">
                <i class="fas fa-check"></i>
                </div>
                <div class="dropdown-item-desc">
                <b>Kusnaedi</b> has moved task <b>Fix bug header</b> to <b>Done</b>
                <div class="time">12 Hours Ago</div>
                </div>
            </a>
            <a href="#" class="dropdown-item">
                <div class="dropdown-item-icon bg-danger text-white">
                <i class="fas fa-exclamation-triangle"></i>
                </div>
                <div class="dropdown-item-desc">
                Low disk space. Let's clean it!
                <div class="time">17 Hours Ago</div>
                </div>
            </a>
            </div>
            <div class="dropdown-footer text-center">
            <a href="#">View All <i class="fas fa-chevron-right"></i></a>
            </div>
        </div>
        </li>
        <li class="dropdown"><a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
        <div class="d-sm-none d-lg-inline-block">Hi, {{Auth()->User()->name}}</div></a>
        <div class="dropdown-menu dropdown-menu-right">
            <a href="{{route('profile.index', Auth::user()->id)}}" class="dropdown-item has-icon">
            <i class="far fa-user"></i> Profile
            </a>
            @if (Auth::user()->isAdmin())
            <a href="{{route('setting.general')}}" class="dropdown-item has-icon">
                    <i class="fas fa-cog"></i> Settings
                </a>
            @endif
            <div class="dropdown-divider"></div>
            <div class="text-center">
                <a class="dropdown-item has-icon text-danger" href="{{ route('logout') }}"
                onclick="event.preventDefault();
                            document.getElementById('logout-form').submit();">
                            {{ __('Logout') }}
                </a>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                @csrf
                </form>
            </div> 
        </div>
        </li>
    </ul>
    </nav>

resources/views/layouts/partials/script.blade.php
<!-- General JS Scripts -->
<script src="{{asset('js/jquery-3.3.1.min.js')}}"></script>
<script src="{{asset('js/popper.min.js')}}"></script>
<script src="{{asset('js/bootstrap.min.js')}}"></script>
<script src="{{asset('js/nicescroll.min.js')}}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
<script src="{{asset('js/stisla.js')}}"></script>
<script src="{{asset('js/Chart.min.js')}}"></script>
<script src="{{asset('js/sweetalert2.all.min.js')}}"></script>

<!-- Template JS File -->
<script src="{{asset('js/scripts.js')}}"></script>
<script src="{{asset('js/custom.js')}}"></script>

<script>
    $(document).ready(function () {
        var msg;
        var success = '{{Session::has('success')}}';
        var fail = '{{Session::has('fail')}}';
        var error = '{{!$errors->isEmpty()}}';

        if (error){
            Swal.fire({
                type: 'error',
                title: 'Oopss...',
                text: 'Your Input Doesn\'t Valid!'
            });
        }
        
        if(success) {
            msg = '{{Session::get('success')}}';
            Swal.fire({
                type: 'success',
                title: 'Success!',
                text: msg
            });
        } else if(fail) {
            msg = '{{Session::get('fail')}}';
            Swal.fire({
                type: 'error',
                title: 'Sorry...',
                text: msg
            });
        }
    });
</script>

resources/views/layouts/partials/sidebar.blade.php
<div class="main-sidebar">
        <aside id="sidebar-wrapper">
          <div class="sidebar-brand">
            <a href="{{route('welcome')}}">i-Rent</a>
          </div>
          <div class="sidebar-brand sidebar-brand-sm">
            <a href="{{route('welcome')}}">iR</a>
          </div>
          <ul class="sidebar-menu">
              <li class="menu-header">Dashboard</li>
              <li class="nav-item dropdown active">
                <a href="#" class="nav-link has-dropdown"><i class="fas fa-fire"></i><span>Dashboard</span></a>
                <ul class="dropdown-menu">
                  <li class="active"><a class="nav-link" href="{{route('home')}}">Main Dashboard</a></li>
                </ul>
              </li>
              <li class="menu-header">Car</li>
              <li class="nav-item dropdown">
                <a href="#" class="nav-link has-dropdown" data-toggle="dropdown"><i class="fas fa-car"></i> <span>Cars</span></a>
                <ul class="dropdown-menu">
                  <li><a class="nav-link" href="{{route('cars.index')}}">All Cars</a></li>
                  @if (!Auth::user()->isUser())
                    <li><a class="nav-link" href="{{route('cars.add')}}">Add New Car</a></li>
                  @endif
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a href="#" class="nav-link has-dropdown" data-toggle="dropdown"><i class="fas fa-layer-group"></i> <span>Brands</span></a>
                <ul class="dropdown-menu">
                  <li><a class="nav-link" href="{{route('cars.brand')}}">All Brands</a></li>
                  @if (!Auth::user()->isUser())
                    <li><a class="nav-link" href="{{route('cars.add.brand')}}">Add New Brand</a></li>
                  @endif
                </ul>
              </li>
              @if (Auth::user()->isAdmin())
                <li class="menu-header">Users</li>
                <li class="nav-item dropdown">
                  <a href="#" class="nav-link has-dropdown" data-toggle="dropdown"><i class="fas fa-user"></i> <span>Users</span></a>
                  <ul class="dropdown-menu">
                    <li><a class="nav-link" href="{{route('users.index')}}">All Users</a></li>
                  </ul>
                </li>
                <li class="nav-item dropdown">
                  <a href="#" class="nav-link has-dropdown" data-toggle="dropdown"><i class="fas fa-user"></i> <span>Workers</span></a>
                  <ul class="dropdown-menu">
                    <li><a class="nav-link" href="{{route('users.workers')}}">All Workers</a></li>
                    @if (!Auth::user()->isUser())
                      <li><a class="nav-link" href="{{route('users.workers.new')}}">Add New Worker</a></li>
                    @endif
                  </ul>
                </li>
              @endif
                @if (!Auth::User()->isAdmin())
                  <li class="menu-header">Transaction</li>
                  <li class="nav-item dropdown">
                    <a href="#" class="nav-link has-dropdown"><i class="fas fa-handshake"></i> <span>Transactions</span></a>
                    <ul class="dropdown-menu">
                      <li><a class="nav-link" href="{{route('trans.borrowed', 'history')}}">History</a></li>
                      @if (Auth::user()->isWorker())
                        <li><a class="nav-link" href="{{route('trans.index')}}">All Transactions</a></li>
                      @endif
                      <li><a class="nav-link" href="{{route('cars.borrowed','recent')}}">Borrowed Car</a></li>
                    </ul>
                  </li>
                @endif
                <li class="menu-header">Settings</li>
                <li class="nav-item dropdown">
                  <a href="#" class="nav-link has-dropdown"><i class="fas fa-user"></i> <span>Profile</span></a>
                  <ul class="dropdown-menu">
                    <li><a class="nav-link" href="{{route('users.profile', Auth::user()->id)}}">Profile</a></li>
                    <li><a class="nav-link" href="{{route('profile.change', Auth::user()->id)}}">Change Profile</a></li>
                    {{-- <li><a class="nav-link beep beep-sidebar" href="components-avatar.html">Recent</a></li> --}}
                  </ul>
                </li>
                {{-- <li class="nav-item dropdown">
                  <a href="#" class="nav-link has-dropdown"><i class="fas fa-cog"></i> <span>settings</span></a>
                    <ul class="dropdown-menu">
                      <li><a class="nav-link" href="{{route('setting.general')}}">General</a></li>
                      @if (Auth::user()->isAdmin())
                        <li><a class="nav-link" href="{{route('setting.advance')}}">Advance</a></li>
                      @endif
                    </ul>
                </li> --}}
            </ul>
        </aside>
      </div>

resources/views/layouts/partials/style.blade.php
@php
$ashver = "#2d4052";
$ash = "#34495e";
$ashdow = "#8ca6bf";
$bluever = "#394eea";
$blue = "#6777ef";
$bluedow = "#acb5f6";
$greenver = "#169d82";
$green = "#1abc9c";
$greendow = "#81d694";
@endphp

<!-- General CSS Files -->
<link rel="stylesheet" href="{{asset('css/bootstrap.min.css')}}">
<link rel="stylesheet" href="{{asset('css/all.min.css')}}">
<link rel="stylesheet" href="{{asset('css/Chart.min.css')}}">


<!-- Template CSS -->
<link rel="stylesheet" href="{{asset('css/style.css')}}">
<link rel="stylesheet" href="{{asset('css/components.css')}}">
<link rel="stylesheet" href="{{asset('css/sweetalert2.min.css')}}">
@auth
<style>

    a {
        @if (Auth::user()->isAdmin())
            color: {{$ash}};
        @elseif(Auth::user()->isWorker())
            color: {{$green}};
        @endif
    }

    a:hover {
        @if (Auth::user()->isAdmin())
            color: {{$ashver}};
        @elseif(Auth::user()->isWorker())
            color: {{$greenver}};
        @endif
    }

    .card .card-header h4 {
        @if (Auth::user()->isAdmin())
            color: {{$ash}};
        @elseif(Auth::user()->isWorker())
            color: {{$green}};
        @endif
    }

    .bg-admin {
        background-color: {{$ash}} !important;
    }

    .btn-user {
        @if (Auth::user()->isAdmin())
            background-color: {{$ash}} !important;
            box-shadow: 0 2px 6px {{$ashdow}};
        @elseif(Auth::user()->isWorker())
            background-color: {{$green}} !important;
            box-shadow: 0 2px 6px {{$greendow}};
        @else
            background-color: {{$blue}} !important;
            box-shadow: 0 2px 6px {{$bluedow}};
        @endif
        color: #fff !important
    }

    .btn-user:hover {
        @if (Auth::user()->isAdmin())
            background-color: {{$ashver}} !important;
        @elseif(Auth::user()->isWorker())
            background-color: {{$greenver}} !important;
        @else
            background-color: {{$bluever}} !important;
        @endif
        color: #fff !important
    }

    body.sidebar-mini .main-sidebar .sidebar-menu > li.active > a {
        @if (Auth::user()->isAdmin())
            background-color: {{$ash}} !important;
            box-shadow: 0 2px 6px {{$ashdow}};
        @elseif(Auth::user()->isWorker())
            background-color: {{$green}} !important;
            box-shadow: 0 2px 6px {{$greendow}};
        @endif
    }

    .navbar-bg {
        @if (Auth::user()->isAdmin())
            background-color: {{$ash}} !important;
        @elseif(Auth::user()->isWorker())
            background-color: {{$green}} !important;
        @endif
    }

    .main-sidebar .sidebar-menu li.active a{
        @if (Auth::user()->isAdmin())
            color: {{$ash}};
        @elseif(Auth::user()->isWorker())
            color: {{$green}};
        @endif
    }

    .main-sidebar .sidebar-menu li ul.dropdown-menu li.active > a {
        @if (Auth::user()->isAdmin())
            color: {{$ash}};
        @elseif(Auth::user()->isWorker())
            color: {{$green}};
        @endif
    }

    .main-sidebar .sidebar-menu li ul.dropdown-menu li a:hover {
        @if (Auth::user()->isAdmin())
            color: {{$ash}};
        @elseif(Auth::user()->isWorker())
            color: {{$green}};
        @endif
    }

    .section .section-title:before {
        @if (Auth::user()->isAdmin())
            background-color: {{$ash}};
        @elseif(Auth::user()->isWorker())
            background-color: {{$green}};
        @endif
    }

</style>
@endauth