routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Notifications\NewUser;

Route::get('/', function () {
    return view('welcome');
    // return redirect()->route('login');
})->name('welcome');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/terms-conditions', 'HomeController@terms')->name('terms');
Route::get('/read-notification/{id}', 'HomeController@readNotification')->name('read-notif');

// PROFILE
Route::group(['prefix' => 'profile', 'as' => 'profile.'], function () {
    Route::get('/{user}', 'HomeController@profile')->name('index');
    Route::get('/edit/{user}', 'HomeController@changeProfile')->name('change');
});

// SETTINGS
Route::group(['prefix' => 'settings', 'as' => 'setting.'], function () {
    Route::get('/general', 'HomeController@general')->name('general');
    Route::get('/advance', 'HomeController@advance')->name('advance');
});

// CARS
Route::group(['prefix' => 'cars', 'as' => 'cars.'], function () {

    Route::get('/', 'CarController@index')->name('index');
    Route::get('/brands', 'BrandController@index')->name('brand');

    Route::get('/add', 'CarController@add')->name('add');
    Route::post('/new', 'CarController@create')->name('new');

    Route::get('/edit/{car}', 'CarController@edit')->name('edit');
    Route::post('/update', 'CarController@update')->name('update');

    Route::get('/delete/{car}', 'CarController@destroy')->name('delete');

    Route::get('/add/brand', 'BrandController@add')->name('add.brand');
    Route::post('/new/brand', 'BrandController@create')->name('new.brand');

    Route::get('/brand/edit/{brand}', 'BrandController@edit')->name('edit.brand');
    Route::post('/brand/update', 'BrandController@update')->name('update.brand');

    Route::get('/brand/delete/{brand}', 'BrandController@destroy')->name('delete.brand');

    Route::get('/detail/{car}/{notif_id?}', 'CarController@detail')->name('detail');

    Route::get('/search', 'CarController@search')->name('search');

    Route::get('/borrow/{car}', 'TransactionsController@borrow')->name('borrow');
    Route::post('/borrowing', 'TransactionsController@borrowing')->name('borrowing');
    Route::get('/borrowed/{type}', 'TransactionsController@borrowed')->name('borrowed');
});

// TRANSACTIONS
Route::group(['prefix' => 'transactions', 'as' => 'trans.'], function () {
    Route::get('/', 'TransactionsController@index')->name('index');
    Route::get('/borrowed/{type}', 'TransactionsController@borrowed')->name('borrowed');

    Route::get('/add/{trans}', 'TransactionsController@add')->name('add');
    Route::post('/new', 'TransactionsController@new')->name('new');

    Route::get('/edit/{trans}', 'TransactionsController@edit')->name('edit');
    Route::post('/update/{trans}', 'TransactionsController@update')->name('update');

    Route::get('/search', 'TransactionsController@search')->name('search');

    Route::get('/take/{trans}', 'TransactionsController@accept')->name('accept');

    Route::get('/delete/{trans}', 'TransactionsController@destroy')->name('delete');

    Route::get('/invoice/{trans}', 'TransactionsController@invoice')->name('invoice');
});

// USERS
Route::group(['prefix' => 'users', 'as' => 'users.'], function () {
    Route::get('/', 'UsersController@index')->name('index');
    Route::get('/workers', 'UsersController@workers')->name('workers');

    Route::get('/profile/{user}', 'UsersController@profile')->name('profile');

    Route::get('/add/{user}', 'UsersController@add')->name('workers.add');
    Route::post('/new', 'UsersController@new')->name('workers.new');

    Route::get('/edit/{user}', 'UsersController@edit')->name('edit');
    Route::post('/update', 'UsersController@update')->name('update');

    Route::get('/search', 'CarController@search')->name('search');

    Route::get('/hire/{user}', 'UsersController@hire')->name('hire');
    Route::get('/kick/{user}', 'UsersController@kick')->name('kick');

    Route::get('/verif/{user}/{type}', 'UsersController@verif')->name('verif');
});


Route::get('/testnotif', function () {
    // Auth::user()->notify(new NewUser(User::find(1)));
    dd(substr(Auth::user()->notifications->first()->type, 18));
})->name('testnotif');

app/Car.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Car extends Model
{
    public function brand()
    {
        return $this->hasOne(Brand::class, 'id', 'id_brand');
    }
    public function getPrice()
    {
        return "Rp." . number_format($this->price);
    }
    
}

app/Http/Controllers/CarController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Car;
use App\Brand;
use App\Transaction;
use Auth;

class CarController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $data['cars'] = Car::paginate(5);
        // dd($data['cars'][0]);
        return view('cars.index', $data);
    }
    public function add()
    {
        $data['brands'] = Brand::All();
        return view('cars.addcar', $data);
    }
    public function create(Request $request)
    {
        // dd($request);
        $request->validate([
            'image' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:4096',
        ]);

        $name = $request->name;
        $brand = $request->brand;
        $plate = $request->plate;
        $img = $request->image;
        $price = (int) str_replace(',','',$request->price);
        $desc = $request->desc;

        $car = new Car;
        $car->name = $name;
        $car->id_brand = $brand;
        $car->price = $price;  
        $car->image = $fileName;
        $car->plate = $plate;
        $car->status = 'Tersedia';
        $car->desc = $desc;

        if($car->save()){

            $img->move(public_path('image'), $fileName);

            return redirect()->route('cars.index')->with('success', 'Mobil Berhasil Dimasukkan!');
        }
        
        return redirect()->back()->with('fail', 'Mobil Gagal Dimasukkan!');

        
    }
    public function edit(Car $car)
    {
        // dd($car);
        $data['brands'] = Brand::All();
        $data['car'] = $car;

        return view('cars.editcar', $data);
    }
    public function update(Request $request)
    {

        $request->validate([
            'image' => 'image|mimes:jpeg,png,jpg,gif,svg|max:4096',
        ]);

        $car = Car::find($id);
        if ($car) {

            $id = $request->id;
            $name = $request->name;
            $brand = $request->brand;
            $price = (int) str_replace(',','',$request->price);
            $desc = $request->desc;

            $car->name = $name;
            $car->brand = $brand;
            $car->price = $price;
            $car->desc = $desc;
            if($request->hasFile('image') && $request->image->isValid()){
                $img = $request->image;
                $fileName = time() . '.' . $img->extension();
                $img->move(public_path('image'), $fileName);
                $car->photo = $fileName;
            }
            if($car->save()){
                
                return redirect()->route('cars.index')->with('success', 'Mobil Berhasil Dimasukkan!');
                // return redirect()->back()->with('success', 'Mobil Berhasil Dimasukkan!');
            }
        }
        return redirect()->back()->with('fail', 'Mobil Gagal Dimasukkan!');

        
    }

    public function destroy(Car $car)
    {
        // dd($car);
        if($car->delete()){
            return redirect()->route('cars.index')->with('success', 'Mobil Berhasil Dihapus!');
        }
    }

    public function search(Request $request)
    {
        // dd($request);
        // $brand = $request->id_brand;
        $car = Car::query();
        // dd($car);
        // $car->where('id_brand', $brand);
        if($request->has('id_brand')){
            $brand = $request->id_brand;
            $car->where('id_brand', $brand);
        }

        if($request->has('q')){
            $query = $request->q;
            $car->where('name', 'LIKE', '%'.$query.'%')
            // ->orWhere('id_brand', $query)
            ->orWhere('price', 'LIKE', '%'.$query.'%')
            ->orWhere('desc', 'LIKE', '%'.$query.'%');
        }
        $result = $car->paginate(5);
        // dd($request->q);
        if(count($result) > 0){
            $data['cars'] = $result;
            return view('cars.index', $data);
        } else {    
            return redirect()->route('cars.index')->with('fail', 'Data Tidak Ditemukan!');
        }
    }

    public function detail(Car $car, $notif_id = null)
    {

        if($notif_id){
            Auth::user()->notifications->where('id', $notif_id)->markAsRead();
        }

        $data['car'] = $car;
        $data['borrowed'] = count(Transaction::where('car_id', $car->id)->get());
        return view('cars.detail', $data);
    }
    public function transactions(Request $request)
    {
        $borrow = new Borrow;
        $borrow->date_first = $request->date_first;
        $borrow->car_id = $request->car;
        $data['car'] = $car;

        return view('transactions.transaction', $data);
    }
}

resources/views/cars/addbrand.blade.php
@extends('layouts.master')
@section('meta-content')
    Brands - Add
@endsection

@push('css')
    <link rel="stylesheet" href="{{asset('css/summernote-bs4.css')}}">
@endpush

@section('content')
    <div class="section-body">
        <h2 class="section-title">Tambah Merk Mobil</h2>
        <p class="section-lead">Halaman Tambah Merk Mobil</p>
        <div class="card">
            <div class="card-header">
                <div class="card-header-action">
                    <a href="{{ url()->previous() }}" class="btn btn-primary btn-lg"><i class="fas fa-arrow-left"></i>&nbsp; Back</a>
                </div>
            </div>
            <div class="card-body">
                <form action="{{route('cars.new.brand')}}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="row">
                        <div class="col-md-12">
                            <div id="image-preview" class="image-preview mr-auto ml-auto mb-4">
                                <label for="image-upload" id="image-label">Choose File</label>
                                <input type="file" name="image" id="image-upload"/>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-12 m-auto">
                            <input type="text" class="form-control text-center" name="name" style="font-size: 3rem">
                        </div>
                    </div>
                    <div class="form-group m-4">
                        <div class="col-sm-12 text-center">
                            <button type="submit" class="btn btn-success"><i class="fas fa-plus"></i>&nbsp; Add Brand</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection


@push('js')
    <script src="{{asset('js/summernote-bs4.min.js')}}"></script>
    <script src="{{asset('js/jquery.uploadPreview.min.js')}}"></script>
    <script>
        "use strict";

        $.uploadPreview({
        input_field: "#image-upload",   // Default: .image-upload
        preview_box: "#image-preview",  // Default: .image-preview
        label_field: "#image-label",    // Default: .image-label
        label_default: "Choose File",   // Default: Choose File
        label_selected: "Change File",  // Default: Change File
        no_label: false,                // Default: false
        success_callback: null          // Default: null
        });
    </script>
@endpush

resources/views/cars/addcar.blade.php
@extends('layouts.master')
@section('meta-content')
    Cars - Add
@endsection

@push('css')
    <link rel="stylesheet" href="{{asset('css/summernote-bs4.css')}}">
@endpush

@section('content')
    <div class="section-body">
        <h2 class="section-title">Tambah Mobil</h2>
        <p class="section-lead">Halaman Tambah Mobil</p>
        <div class="card">
            <div class="card-header">
                <div class="card-header-action">
                    <a href="{{ url()->previous() }}" class="btn btn-primary btn-lg"><i class="fas fa-arrow-left"></i>&nbsp; Back</a>
                </div>
            </div>
            <div class="card-body">
                <form action="{{route('cars.new')}}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3 pt-2">Name</label>
                        <div class="col-sm-12 col-md-7">
                            <input type="text" name="name" class="form-control">
                        </div>
                    </div>
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3 pt-2">Brand</label>
                        <div class="col-sm-12 col-md-7">
                            <select name="brand" class="form-control selectric">
                            @foreach ($brands as $brand)
                                <option value="{{$brand->id}}">{{ucfirst($brand->name)}}</option>
                            @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3 pt-2">Plate</label>
                        <div class="col-sm-12 col-md-7">
                            <input type="text" name="plate" class="form-control plate">
                        </div>
                    </div>
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3 pt-2">Image</label>
                        <div class="col-sm-12 col-md-7">
                            <div id="image-preview" class="image-preview">
                                <label for="image-upload" id="image-label">Choose File</label>
                                <input type="file" name="image" id="image-upload"/>
                            </div>
                        </div>
                    </div>
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3 pt-2">Currency</label>
                        <div class="input-group col-sm-12 col-md-7">
                            <div class="input-group-prepend">
                                <div class="input-group-text">
                                    Rp.
                                </div>
                            </div>
                            <input type="text" name="price" class="form-control currency">
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    / day
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group row mb-4">
                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Content</label>
                        <div class="col-sm-12 col-md-7">
                            <textarea name="desc" class="summernote-simple"></textarea>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-12 col-md-10 text-md-right">
                            <button type="submit" class="btn btn-success"><i class="fas fa-plus"></i>&nbsp; Add Car</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection


@push('js')
    <script src="{{asset('js/summernote-bs4.min.js')}}"></script>
    <script src="{{asset('js/cleave.min.js')}}"></script>
    <script src="{{asset('js/jquery.uploadPreview.min.js')}}"></script>
    <script>
        "use strict";

        $.uploadPreview({
        input_field: "#image-upload",   // Default: .image-upload
        preview_box: "#image-preview",  // Default: .image-preview
        label_field: "#image-label",    // Default: .image-label
        label_default: "Choose File",   // Default: Choose File
        label_selected: "Change File",  // Default: Change File
        no_label: false,                // Default: false
        success_callback: null          // Default: null
        });
        var cleaveC = new Cleave('.currency', {
            numeral: true,
            numeralThousandsGroupStyle: 'thousand'
            });
        var cleaveP = new Cleave('.plate', {
            blocks: [1, 4, 2],
            uppercase: true,
            delimiter: ' - ',
            delimiterLazyShow: true
        });
    </script>
@endpush

resources/views/cars/brands.blade.php
@extends('layouts.master')
@section('meta-content')
    Car's Brands
@endsection
@push('css')
<style>
    .brand-box:hover{
        background-color: whitesmoke;
    }
</style>    
@endpush
@section('content')
<div class="section-body">
    <h2 class="section-title">Halaman Merk</h2>
    <p class="section-lead">List Semua Merk yg terdata di Database</p>
        <div class="row">
            <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <div class="card-header-action w-100">
                                <a href="{{ url()->previous() }}" class="btn btn-primary btn-lg"><i class="fas fa-arrow-left"></i>&nbsp; Back</a>
                                @if (!Auth::user()->isUser())
                                <a href="{{ route('cars.add.brand') }}" class="btn btn-warning btn-lg float-right"><i class="fas fa-plus"></i>&nbsp; Tambah</a>
                                @endif
                                
                            </div>
                        </div>
                    </div>    
            </div>
            @if (count($brands) > 0)
                @foreach ($brands as $brand)
                <div class="col-md-4 text-center mb-4 brand-box">
                        <div class="card h-100 card-body" style="min-height: 200px">
                            @if (!Auth::user()->isUser())
                            <a class="ml-auto mr-1 brand-delete" style="color: #aaa" href="#" data-id="{{$brand->id}}"><i class="fas fa-times"></i></a>
                            @endif
                            <img src="{{asset('image/' . $brand->photo)}}" alt="{{$brand->name}}" class="d-block w-50 m-auto" style="max-height: 250px">
                            <a href="{{route('cars.search', ['id_brand' => $brand->id])}}" class="btn btn-lg m-4 btn-user " style="font-size: 1em">{{ucfirst($brand->name)}}</a>
                        </div>
                </div>
                @endforeach
            @else
                <div class="col-md-12 text-center mt-5">
                    <h3 class="title">Data Masih Kosong!</h3>
                    <a href="#" class="btn btn-lg btn-success mt-2 mb-5"><span class="fas fa-plus"></span>&nbsp; Tambah</a>
                </div>
            @endif
        </ul>
        </div>
</div>
@endsection

@push('js')
    <script>
        $('.brand-delete').each(function (i) {
            const id = $(this).data('id');
            $(this).click(function(e){
                e.preventDefault();
                Swal.fire({
                    title: 'Anda Yakin?',
                    text: "Data mobil terkait juga akan ikut hilang!",
                    type: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#ffa426',
                    cancelButtonColor: '#fc544b',
                    confirmButtonText: 'Ya, Saya Yakin!'
                    }).then((result) => {
                        if (result.value) {
                            window.location = "{{url('/cars')}}" + '/brand/delete/' + id;
                        } else if (result.dismiss === Swal.DismissReason.cancel){
                            Swal.fire(
                            'Hapus Digagalkan!',
                            'Anda Tidak Jadi Menghapus Brand',
                            'success'
                            );
                        }
                    });
                });
            }); 
    </script>
@endpush

resources/views/cars/detail.blade.php
@extends('layouts.master')
@section('meta-content')
Cars - Detail
@endsection
@section('content')
<div class="section-body">
    <h2 class="section-title">Detail Mobil</h2>
    <p class="section-lead">Berisi semua data mobil terkait</p>
    <div class="card">
        <div class="card-header">
            <img class="m-auto" src="{{asset('image') . '/' . $car->image}}" alt="{{$car->name}}" style="max-width: 100%">
        </div>
        <div class="card-body">
            <div class="container text-center mb-5">
                <h4>{{$car->name}}</h4>
                <img src="{{asset('image') . '/' . $car->brand->photo}}" alt="{{$car->brand->name}}" width="50">
            </div>
            <div class="row">
                <div class="col-6 col-md-6 col-sm-12 row">
                    <div class="col-6 col-md-12 col-sm-6">
                        <span style="font-size: 1.2rem">Car's Name : </span><br><br>
                        {{$car->name}}
                    </div>
                    <div class="col-6 col-md-12 col-sm-6">
                        <span style="font-size: 1.2rem">Car's Brand : </span><br><br>
                        {{$car->brand->name}}
                    </div>
                </div>
                <div class="col-6 col-md-6 col-sm-12 text-center">
                    <span style="font-size: 1.2rem">Description : </span><br><br>
                    {{$car->desc}}
                </div>
                <div class="col-12 mt-5 mb-2">
                    <hr>
                </div>
                <div class="col-6 col-md-6 col-sm-12 mt-4 text-center">
                    <span style="font-size: 1.2rem">Plate : </span><br>
                    <h4>{{$car->plate}}</h4>
                </div>
                <div class="col-6 col-md-6 col-sm-12 mt-4 text-center">
                    <span style="font-size: 1.2rem">Price / Day : </span ><br>
                        <h4>{{$car->getPrice()}}</h4>
                    </div>
                    <div class="col-12 mt-4 mb-4 text-center">
                        <span style="font-size: 1.2rem">Borrowed : </span ><br>
                            <h4>{{$borrowed}}</h4>
                        </div>
                        <div class="col-12 mb-2">
                            <hr>
                        </div>
                    </div>
                    * Data Updated At {{$car->updated_at}}.
                </div>
                <div class="card-footer text-md-right text-sm-center">
                    @if ($car->status == 'tersedia')
                    <a href="{{route('cars.borrow', [$car->id])}}" class="btn btn-success btn-action mr-1" data-toggle="tooltip" title="Borrow"><i class="fas fa-car-side"></i> Borrow Now</a>
                    @endif
                    <a href="{{route('cars.edit', [$car->id])}}" class="btn btn-primary btn-action mr-1" data-toggle="tooltip" title="Edit"><i class="fas fa-pencil-alt"></i> Edit Data</a>
                </div>
            </div>
        </div>
        @endsection

resources/views/cars/index.blade.php
{{-- @php
    dd(old());
@endphp --}}
@extends('layouts.master')
@section('meta-content')
    Cars
@endsection
@section('content')
    <div class="section-body">
        <h2 class="section-title">Halaman Mobil</h2>
        <p class="section-lead">Berisi semua data mobil yang terdata di database</p>
        <div class="card">
            <div class="card-header">
                @if (!Auth::user()->isUser())
                <a href="{{route('cars.add')}}" class="btn btn-warning btn-lg"><i class="fas fa-plus"></i>&nbsp; Tambah</a>
                <h4></h4>
                @else
                <h4>Data Mobil</h4>
                @endif
                <div class="card-header-form">
                    <form action="{{route('cars.search')}}" method="get">
                    <div class="input-group">
                        <input type="text" name="q" class="form-control" value="{{old('q', '')}}" placeholder="Search">
                        <div class="input-group-btn">
                        <button type="submit" class="btn btn-info"><i class="fas fa-search"></i></button>
                        </div>
                    </div>
                    </form>
                </div>
            </div>
            <div class="card-body p-0">
                <div class="table-responsive">
                    @if(count($cars) > 0)
                        <table class="table table-hover">
                            <thead class="table-thead">
                                <tr>
                                    <th>No.</th>
                                    <th>Nama</th>
                                    <th>Merk</th>
                                    <th>Harga/hari</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody class="table-tbody">
                                @foreach ($cars as $car)
                                    <tr>
                                        <td>{{$loop->iteration}}</td>
                                        <td>{{$car->name}}</td>
                                        <td>{{ucfirst($car->brand->name)}}</td>
                                        <td>{{$car->getPrice()}}</td>
                                        <td>
                                            <a href="{{route('cars.detail', [$car->id])}}" class="btn btn-secondary btn-action mr-1" data-toggle="tooltip" title="Detail"><i class="fas fa-eye"></i></a>
                                            @if (!Auth::user()->isUser())
                                                <a href="{{route('cars.edit', [$car->id])}}" class="btn btn-primary btn-action mr-1" data-toggle="tooltip" title="Edit"><i class="fas fa-pencil-alt"></i></a>
                                                @if (Auth::user()->isWorker())
                                                    <a href="{{route('cars.borrow', [$car->id])}}" class="btn btn-success btn-action mr-1" data-toggle="tooltip" title="Borrow"><i class="fas fa-car-side"></i></a>
                                                @endif
                                                <a href="#" class="btn btn-danger btn-action car-delete" data-toggle="tooltip" data-id="{{$car->id}}" title="Delete"><i class="fas fa-trash"></i></a>
                                            
                                            @else
                                            <a href="{{route('cars.borrow', [$car->id])}}" class="btn btn-success btn-action" data-toggle="tooltip" title="Borrow"><i class="fas fa-car-side"></i></a>
                                            @endif
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                        <div class="float-right pr-3">
                            {{$cars->links()}}
                        </div>
                    @else
                        <div class="col-md-12 text-center mt-5">
                            <h3 class="title">Data Masih Kosong!</h3>
                            <a href="#" class="btn btn-lg btn-success mt-2 mb-5"><span class="fas fa-plus"></span>&nbsp; Tambah</a>
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
@endsection

@push('js')
    <script>
        $('.car-delete').each(function (i) {
            const id = $(this).data('id');
            $(this).click(function(e){
                e.preventDefault();
                Swal.fire({
                    title: 'Anda Yakin?',
                    text: "Proses ini tidak bisa dikembalikan!",
                    type: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#ffa426',
                    cancelButtonColor: '#fc544b',
                    confirmButtonText: 'Ya, Saya Yakin!'
                    }).then((result) => {
                        if (result.value) {
                            window.location = "{{url('/cars')}}" + '/delete/' + id;
                        } else if (result.dismiss === Swal.DismissReason.cancel){
                            Swal.fire(
                            'Hapus Digagalkan!',
                            'Data Mobil Diselamatkan!',
                            'success'
                            );
                        }
                    });
                });
            }); 
    </script>
@endpush